#!/bin/sh
#############################################################################
# Script containing several functions related to zfs snapshots
#
# Author: fritz from NAS4Free forum
#############################################################################

# Initialisation of constants
readonly DATE_FORMAT_ZFS="%a %b %d %H:%M %Y" 	# format of the snapshot creation date as provided by the 'zfs list -o creation' function
						# example: Wed Dec 29 22:59 2010
readonly DATE_FORMAT_SNAP_NAME="%Y%m%d_%H%M"	# format of the creation date in the snapshot name

################################## 
# Return the sorted list of the snaptshots for
# the filesystem (not recursively)
# The new snapshots are returned first
#
# Param 1: filesystem
# Param 2: snapshotTag (or empty string if allsnapshots should be returned)
# Return : The sorted list of snapshots
##################################
sortSnapshots() {
	local filesystem snapshotTag

	filesystem="$1"
	snapshotTag="$2"

	# sort the snapshot based on the "creation" attribute
	$BIN_ZFS list -H -o name -S creation -t snapshot -d 1 -r $filesystem \
		| grep "^$filesystem@[0-9]\{8,8\}_[0-9]\{4,4\}_autosnap_$snapshotTag"
}

################################## 
# Get the snapshot creation date
# (in seconds sice 1970)
#
# Param 1: snapshot name
# Return : creation date in s since 1970
##################################
getSnapTimestamp1970() {
	local snapshotName creationDate
	
	snapshotName="$1"
	creationDate=`$BIN_ZFS list -t snapshot -H -o creation "$snapshotName"`
	
	$BIN_DATE -j -f "$DATE_FORMAT_ZFS" "$creationDate" +"%s"
}

################################## 
# Generate a snapshot name
# (the name of a snapshot to be created shall always get generated by
# this function in order to ensure that it has the right format)
# This function only returns the part after the "@" character
#
# Param 1: snapshot tag
# Param 2: timestamp (in seconds since 1970)
# Return : the snapshot name
##################################
generateSnapshotName() {
	local tag ts tsFormatted

	tag="$1"
	ts="$2"

	tsFormatted=`$BIN_DATE -j -f "%s" "$ts" +"$DATE_FORMAT_SNAP_NAME"`

	echo "$tsFormatted"_autosnap_"$tag"
}

####################################################################
# Change Notes:
#
# 2010-08-21:
#	- Creation of the change notes
#	- Functions available: "convertTimestamp", "sortSnapshots", 
#	  "getSnapTimestamp" and "getSnapTimestamp1970"
# 2010-12-30:
#	- Script adapted for FreeNAS 0.7.2 (was for open solaris before) 
# 2011-01-01:
#	- Bug fix in function "getSnapTimestamp1970" 
# 2011-01-03:
#	- Bug fix in function "getTimestampFormat" (format changed 
#	  from "%G%m%d_%H%M" to "%Y%m%d_%H%M") 
# 2012-12-17:
#	- constants defining path to utilities (like date, rm...) moved to config.sh
# 2012-12-25:
#	- performance of function sortSnapshots improved
# 2013-01-03:
#       - new snapshot naming rules to be compatible with NAS4Free
#         CIFS shadow copies function:
#	  new function "generateSnapshotName"
#	  function "sortSnapshots" modified 
# 2013-01-06:
#       - code of function sortSnapshots simplified
#	- fcts "convertTimestamp", "getSnapTimestamp" and ""getTimestampFormat"" deleted
# 2013-01-08:
#       - minor changes in declaration of local variables
# 2013-01-13:
#       - few variables declared readonly
####################################################################
