#!/bin/sh
#############################################################################
# Script containing several functions related to zfs snapshots
#
# Author: fritz from NAS4Free forum
#############################################################################

# Initialisation of constants
readonly DATE_FORMAT_ZFS="%a %b %d %H:%M %Y" 	# format of the snapshot creation date as provided by the 'zfs list -o creation' function
						# example: Wed Dec 29 22:59 2010
readonly DATE_FORMAT_SNAP_NAME="%Y%m%d_%H%M"	# format of the creation date in the snapshot name

################################## 
# Return the sorted list of the snaptshots for
# the filesystem (not recursively)
# The new snapshots are returned first
#
# Param 1: filesystem
# Param 2: snapshotTag (or empty string if allsnapshots should be returned)
# Return : The sorted list of snapshots
##################################
sortSnapshots() {
	local filesystem snapshotTag

	filesystem="$1"
	snapshotTag="$2"

	# sort the snapshot based on the "creation" attribute
	$BIN_ZFS list -H -o name -S creation -t snapshot -d 1 -r $filesystem \
		| grep "^$filesystem@[0-9]\{8,8\}_[0-9]\{4,4\}_autosnap_$snapshotTag"
}

################################## 
# Get the snapshot creation date
# (in seconds sice 1970)
#
# Param 1: snapshot name
# Return : creation date in s since 1970
##################################
getSnapTimestamp1970() {
	local snapshotName creationDate
	
	snapshotName="$1"
	creationDate=`$BIN_ZFS list -t snapshot -H -o creation "$snapshotName"`
	
	$BIN_DATE -j -f "$DATE_FORMAT_ZFS" "$creationDate" +"%s"
}

################################## 
# Generate a snapshot name
# (the name of a snapshot to be created shall always get generated by
# this function in order to ensure that it has the right format)
# This function only returns the part after the "@" character
#
# Param 1: snapshot tag
# Param 2: timestamp (in seconds since 1970)
# Return : the snapshot name
##################################
generateSnapshotName() {
	local tag ts tsFormatted

	tag="$1"
	ts="$2"

	tsFormatted=`$BIN_DATE -j -f "%s" "$ts" +"$DATE_FORMAT_SNAP_NAME"`

	echo "$tsFormatted"_autosnap_"$tag"
}

